include:
  - local: accounts.gitlab-ci.yml
    rules:
      - if: ($CI_COMMIT_TAG || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH) && $CI_PIPELINE_SOURCE != 'merge_request_event'
  - local: changes.gitlab-ci.yml
    rules:
      - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
