include:
  - local: common.gitlab-ci.yml

#### templates

.terra_all_template:
  needs: []
  extends:
    - .common_terragrunt_all_template
    - .common_terraform_modules
    - .accounts_groups

.accounts_groups:
  parallel:
    matrix:
      - TERRA_GROUP_NAME:
          - audit
          - camp
          - data
          - infra.camp
          - infra.data-platform
          - infra.iva
          - infra.ocam
          - infra.opr
          - infra.platform
          - infra.pqs
          - infra.visas
          - iva
          - logs
          - management.camp
          - management.data-platform
          - management.iva
          - management.ocam
          - management.opr
          - management.platform
          - management.pqs
          - management.visas
          - network
          - ocam
          - opr
          - platform_sandbox
          - pqs
          - prod
          - subordinateca
          - visas

#### lint

validate-terraform-inputs-accounts:
  extends:
    - .terra_all_template
    - .validate_terraform_inputs

#### validate

validate-terragrunt-units-accounts:
  extends:
    - .terra_all_template
    - .validate_terragrunt_units

#### test

test-terragrunt-units-accounts:
  extends:
    - .terra_all_template
    - .test_terragrunt_units

#### plan

plan-terragrunt-accounts:
  extends:
    - .terra_all_template
    - .plan_terragrunt_units

##### publish plan

publish-plan-terragrunt-accounts:
  needs:
    - plan-terragrunt-accounts
  extends:
    - .common_terragrunt_all_template
    - .publish_plan_terragrunt_units
#### apply

# apply-terragrunt-accounts:
#   rules:
#     - if: ($CI_COMMIT_TAG || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH) && $CI_PIPELINE_SOURCE != 'merge_request_event'
#       exists:
#         - "**/*.hcl"
#       when: manual
#   extends:
#     - .terra_all_template
#     - .apply_terragrunt_units
#   needs:
#     - detect_changes
#     - plan-terragrunt-accounts
#     - publish-plan-terragrunt-accounts
